apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  chart:
    spec:
      version: "v0.12.1"
  test:
    enable: false
  values:
    # configInline:
    #   address-pools:
    #   - name: default
    #     protocol: layer2
    #     addresses:
    #     - 192.168.122.10-192.168.122.19
